function SectionP() {
    return (
        <>
            <div className="flex items-center justify-center px-4 py-12">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dis rhoncus porttitor pharetra, aliquam malesuada vitae odio gravida placerat. Auctor id etiam ullamcorper tempus, scelerisque. Lorem phasellus donec laoreet egestas. Vulputate in nulla laoreet mauris fermentum nunc metus. Mauris sem dui, varius in mi interdum. Non amet dolor imperdiet etiam nullam mauris sollicitudin. Eu at adipiscing quam non congue nunc. Quisque gravida quis suspendisse scelerisque tincidunt. Viverra bibendum amet senectus orci.
                </p>
            </div>
        </>
    )
}
export default SectionP